# Copyright (C) Barnes Group Inc. - All Rights Reserved
# 
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Tubio-Pardavila, Ricardo; ricardo-tubio@oenbarnes.com, 03.04.2024

version: '3'

vars:

  # Common user directory tree
  USER_NAME:
    sh: whoami
  USER_HOME:
    sh: echo $HOME
  CONF_DIR:           '{{.USER_HOME}}/.config'
  LOCAL_DIR:          '{{.USER_HOME}}/.local'
  ETC_DIR:            '{{.LOCAL_DIR}}/etc'
  SHARE_DIR:          '{{.LOCAL_DIR}}/share'
  VAR_DIR:            '{{.LOCAL_DIR}}/var'
  LOG_DIR:            '{{.VAR_DIR}}/log'
  SPOOL_DIR:          '{{.VAR_DIR}}/spool'
  # Wakame directory strucure (user directory tree)
  WAKAME_CONF_DIR:    '{{.CONF_DIR}}/wakame'
  WAKAME_LOG_DIR:     '{{.LOG_DIR}}/wakame'
  WAKAME_LOG_FILE:    '{{.LOG_DIR}}/wakame.log'
  WAKAME_TASKS_DIR:   '{{.SHARE_DIR}}/wakame'
  WAKAME_TASK:        '{{.WAKAME_TASKS_DIR}}/taskfile.yml'
  # Anacron directory strucure (user directory tree)
  ANACRON_DAILY:      '{{.ETC_DIR}}/cron.daily'
  ANACRON_CONF:       '{{.ETC_DIR}}/anacrontab'
  ANACRON_SPOOL_DIR:  '{{.SPOOL_DIR}}/spool/anacron'
  # Daily anacron scripts for system maintenance
  ANACRON_DOCKER_DAILY:  '{{.ANACRON_DAILY}}/docker-cleanup.sh'

includes:

  anacron:  '{{.PWD}}/tasks/anacron.yml'
  docker:   '{{.PWD}}/tasks/docker.yml'
  users:    '{{.PWD}}/tasks/users.yml'

tasks:

  default:
    cmds:
      - echo "Installing local resources..."
      - task: setup
      - task: deploy
      - task: anacron:setup
      - task: docker:anacron
      - echo "See the list of available tasks with = task --list"

  setup:
    desc: Installs the script resources in the local OS
    internal: true
    status:
      - test -d '{{.WAKAME_CONF_DIR}}'
      - test -d '{{.WAKAME_TASKS_DIR}}'
      - test -d '{{.WAKAME_LOG_DIR}}'
    cmds:
      - mkdir -p '{{.WAKAME_CONF_DIR}}'
      - mkdir -p '{{.WAKAME_TASKS_DIR}}'
      - mkdir -p '{{.WAKAME_LOG_DIR}}'

  deploy:
    desc: (overrides) Deploys the source code in the target directory
    prompt: This task should only be called from within the GIT repository root, are you there?
    cmds:
      - cp -Rf {{.PWD}}/* {{.SHARE_DIR}}/wakame/.
